import type { Shampoo } from "./types.js";

export const mockShampoos: Shampoo[] = [
  {
    id: 1,
    name: "SALON BEAUTY для ухода за волосами с экстрактом ламинарии",
    brandNote: "Ollin Professional",
    score: 42,
    price: 804,
    fit: ["normal"],
    base: "Базовый SLES-шампунь старого типа без заметного преимущества за свою цену.",
    signals: ["простая SLES-база", "Cocamide DEA", "MCI/MI"],
    verdict: "Формула должна нормально пениться и промывать: есть SLES, CAPB, соль, Glycol Distearate и Laureth-4 для текстуры. Ламинария и пропиленгликоль добавлены, но не выглядят ключевыми для качества.",
    caution: "Состав выглядит довольно бюджетно: Cocamide DEA, MCI/MI, отдушка и минимум полезного кондиционирования. Экстракт ламинарии стоит ближе к концу и не делает формулу заметно лучше. За 804 руб/л это слабый кандидат на фоне более удачных составов.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Cocamide DEA, Glycol Distearate, Laureth-4, Parfum, Citric Acid, Tetrasodium EDTA, Propylene Glycol, Laminaria Saccharina Extract, Magnesium Nitrate, Magnesium Chloride, Methylchloroisothiazolinone, Methylisothiazolinone, Linalool",
  },
  {
    id: 2,
    name: "Шампунь и бальзам для волос женский 2в1 мицеллярный",
    brandNote: "Чистая линия",
    score: 45,
    price: 377,
    fit: ["normal"],
    base: "Недорогой 2в1-шампунь с обычной SLES-базой и спорным порядком компонентов.",
    signals: ["дешёвый 2в1", "спорный INCI", "красители"],
    verdict: "Есть рабочие компоненты для повседневного мытья: SLES, CAPB, Sodium Cocoamphoacetate, Glycerin и Polyquaternium-10. За низкую цену это может быть приемлемый простой вариант.",
    caution: "Sodium Chloride стоит очень высоко, а экстракты и масла перечислены раньше части базовых ПАВ, что выглядит странно и снижает доверие к карточке. Cocamide DEA, отдушка и красители не добавляют качества. Как 2в1 может быть приемлем, но формульно это не лидер.",
    inci: "Aqua, Sodium Laureth Sulfate, Sodium Chloride, Achillea Millefolium Extract, Chamomilla Recutita Flower Extract, Chelidonium Majus Extract, Helianthus Annuus Seed Oil, Hydrolyzed Cottonseed Extract, Hypericum Perforatum Flower Leaf Stem Extract, Panthenol, Urtica Dioica Leaf Extract, Citric Acid, Cocamide DEA, Cocamidopropyl Betaine, Disodium EDTA, Glycerin, Parfum, Phenoxyethanol, Polyquaternium-10, Sodium Benzoate, Sodium Cocoamphoacetate, CI 19140, CI 42090",
  },
  {
    id: 3,
    name: "PURITY DETOXIFYING SHAMPOO",
    brandNote: "Yves Rocher",
    score: 84,
    price: 1723,
    fit: ["normal", "oily"],
    base: "Один из лучших мягких бессульфатных составов в рейтинге: современная ПАВ-база без силиконов и тяжёлого кондиционирования.",
    signals: ["сильный sulfate-free", "мягкая ПАВ-база", "дорогой за литр"],
    verdict: "Формула собрана аккуратно: Sodium Methyl Cocoyl Taurate, CAPB, Sodium Cocoyl Isethionate, Lauryl Glucoside и Coco-Glucoside дают мягкое очищение без классических сульфатов. Есть Glycerin, Guar Hydroxypropyltrimonium Chloride и Glyceryl Oleate для смягчения и скольжения.",
    caution: "Цена заметно выше многих конкурентов, а Detox — скорее маркетинговое позиционирование. Отдушка стоит довольно высоко, pH не указан, а экстракт водорослей и токоферол не стоит переоценивать. Хороший состав, но не обязательно лучший value.",
    inci: "Aqua, Sodium Methyl Cocoyl Taurate, Cocamidopropyl Betaine, Sodium Cocoyl Isethionate, Lauryl Glucoside, Parfum, Asparagopsis Armata Extract, Sodium Benzoate, Glycerin, Citric Acid, Guar Hydroxypropyltrimonium Chloride, Sodium Chloride, Coco-Glucoside, Glyceryl Oleate, Potassium Sorbate, Limonene, Tocopheryl Acetate, Hydrogenated Vegetable Glycerides Citrate, Tocopherol",
  },
  {
    id: 4,
    name: "Шампунь для волос нейтральный pH-Баланс",
    brandNote: "LIBREDERM",
    score: 60,
    price: 1761,
    fit: ["normal"],
    base: "Нормальный, но дорогой SLES-шампунь с хорошими смягчающими добавками и старым консервантом MCI/MI.",
    signals: ["pH заявлен размыто", "есть смягчение", "дорого за состав"],
    verdict: "SLES и CAPB дополнены глицерином, Sodium Lauroyl Oat Amino Acids, пантенолом, aloe, cationic guar, Coco-Glucoside и Glyceryl Oleate. Это делает формулу мягче и приятнее, чем простой бюджетный SLES-шампунь.",
    caution: "Cocamide DEA стоит высоко, pH назван «нейтральным», но точное значение не указано. Есть Methylchloroisothiazolinone и Methylisothiazolinone. Растительные экстракты выглядят второстепенно, а цена высокая для такой архитектуры.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Cocamide DEA, Sodium Chloride, Glycerin, Sodium Lauroyl Oat Amino Acids, Panthenol, Aloe Barbadensis Leaf Juice, Rosa Canina Fruit Extract, Passiflora Incarnata Flower Extract, Hydroxypropyl Guar Hydroxypropyltrimonium Chloride, Propylene Glycol, Coco-Glucoside, Glyceryl Oleate, Citric Acid, Magnesium Nitrate, Methylchloroisothiazolinone, Magnesium Chloride, Methylisothiazolinone, Tetrasodium EDTA",
  },
  {
    id: 5,
    name: "OLLIN SERVICE LINE ежедневный уход PH 5.5",
    brandNote: "Ollin Professional",
    score: 12,
    price: 952,
    fit: ["normal"],
    base: "Формально обычный SLES-шампунь с pH 5.5, но состав не подходит для рейтинга актуальных современных формул из-за Lilial.",
    signals: ["pH 5.5", "красный флаг", "не рекомендуется"],
    verdict: "База сама по себе не катастрофическая: SLES, CAPB, Lauryl Glucoside и Polyquaternium-7 могли бы дать нормальный повседневный шампунь.",
    caution: "Butylphenyl Methylpropional / Lilial — главный красный флаг, запрещённый в Евросоюзе. Дополнительно есть Methylchloroisothiazolinone и Methylisothiazolinone. pH 5.5 не спасает формулу.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Lauryl Glucoside, Polyquaternium-7, Citric Acid, Parfum, Dicaprylyl Ether, Lauryl Alcohol, Tetrasodium EDTA, Linalool, Butylphenyl Methylpropional, Hexyl Cinnamal, Magnesium Nitrate, Magnesium Chloride, Methylchloroisothiazolinone, Methylisothiazolinone",
  },
  {
    id: 6,
    name: "Шампунь для объема волос Basil & Mandarin",
    brandNote: "SOKOLOV",
    score: 53,
    price: 826,
    fit: ["normal"],
    base: "Перегруженный SLES-шампунь с поликватами, силиконом, эфирными маслами и маркетинговым хвостом.",
    signals: ["перегруженный состав", "MCI/MI", "спорно для объёма"],
    verdict: "Есть рабочая база SLES + CAPB, глицерин, бетаин, несколько polyquaternium-компонентов и PEG-12 Dimethicone, поэтому шампунь может давать гладкость и приятную сенсорику.",
    caution: "Для шампуня «для объёма» состав выглядит спорно: много кондиционирующих полимеров и силикон могут утяжелять. Cocamide DEA, эфирные масла базилика и мандарина, коллоидное серебро, MCI/MI и длинный витаминный хвост делают формулу менее чистой и менее предсказуемой.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Polyquaternium-7, Styrene/Acrylates Copolymer, Cocamide DEA, Glycerin, PEG-120 Methyl Glucose Dioleate, Sodium Chloride, PEG-12 Dimethicone, Parfum, Polyquaternium-16, Polyquaternium-44, Betaine, Malic Acid, Succinic Acid, Lactic Acid, Ocimum Basilicum Oil, Calcium Pantothenate, Niacinamide, Citrus Nobilis Peel Oil, Sodium Ascorbyl Phosphate, Pyridoxine HCl, Tocopheryl Acetate, Colloidal Silver, Silica, Acacia Senegal Gum, Sodium Starch Octenylsuccinate, Methylisothiazolinone, Disodium EDTA, Sodium Hydroxide, Maltodextrin, Methylchloroisothiazolinone, Limonene, Linalool, Hexyl Cinnamal",
  },
  {
    id: 7,
    name: "Шампунь для волос",
    brandNote: "Rudakov A.A.",
    score: 18,
    price: 195,
    fit: ["normal"],
    base: "Состав оформлен как псевдо-INCI с декоративными переводами, поэтому доверие к карточке низкое.",
    signals: ["очень дешёвый", "низкое доверие составу"],
    verdict: "Видна обычная SLES/CAPB-база с Polyquaternium-7, глицерином и пантенолом.",
    caution: "Формат состава на карточке ВБ вроде «вода живая», «мыльный створ», «зелье от порчи» — красный флаг достоверности. Плюс есть Cocamide DEA, MCI/MI, минеральное масло, Cetrimonium Chloride и тяжёлые кондиционирующие компоненты.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Polyquaternium-7, Sodium Chloride, Glycerin, Cocamide DEA, Panthenol, Urtica Dioica Leaf Extract, Aloe Barbadensis Leaf Extract, Parfum, Tetrasodium EDTA, Citric Acid, Methylchloroisothiazolinone, Methylisothiazolinone, Cetearyl Alcohol, Paraffinum Liquidum, Stearamidopropyl Dimethylamine, Cetrimonium Chloride, Phenoxyethanol",
  },
  {
    id: 8,
    name: "Шампунь для роста волос с розмарином против выпадения",
    brandNote: "Likato professional",
    score: 41,
    price: 758,
    fit: ["oily"],
    base: "Жёстко-очищающий и перегруженный шампунь с розмарином, ментолом, спиртом, красителями и MCI/MI.",
    signals: ["Sodium Coco-Sulfate", "ментол и спирт", "claim против выпадения слабый"],
    verdict: "Есть несколько смягчающих компонентов: CAPB, Sodium Cocoamphoacetate, Coco-Glucoside, Polyquaternium-7, Glycereth-2 Cocoate, Silicone Quaternium-17, сорбитол и глицерин.",
    caution: "Sodium Coco-Sulfate в начале делает базу более жёсткой. Menthol, Isopropyl Alcohol, эфирно-травяной блок, красители и MCI/MI повышают риск раздражения. Заявление против выпадения по составу выглядит слабым: розмарин, кофеин и экстракты в шампуне не доказывают реального влияния на выпадение волос.",
    inci: "Aqua, Sodium Coco-Sulfate, Cocamidopropyl Betaine, Sodium Cocoamphoacetate, Cocamide DEA, Coco-Glucoside, Polyquaternium-7, Sodium Lauryl Sarcosinate, Sorbitol, Glycereth-2 Cocoate, Aloe Barbadensis Leaf Juice, Chamomilla Recutita Flower Extract, Melissa Officinalis Leaf Extract, Thymus Serpyllum Extract, Rosmarinus Officinalis Leaf Extract, Propylene Glycol, Persea Gratissima Oil, Olea Europaea Fruit Oil, Parfum, Silicone Quaternium-17, Trideceth-7, Trideceth-5, Sodium Chloride, Urea, Caffeine, Menthol, Isopropyl Alcohol, Methylchloroisothiazolinone, Methylisothiazolinone, Sodium Salicylate, Citric Acid, CI 19140, CI 42090, EDTA",
  },
  {
    id: 9,
    name: "Шампунь для волос с крапивой и алоэ",
    brandNote: "Faberlic",
    score: 36,
    price: 465,
    fit: ["normal"],
    base: "Тяжёлый шампунь-кондиционер с силиконами и катионными компонентами высоко в составе.",
    signals: ["много силиконов", "риск утяжеления", "DMDM + MCI/MI"],
    verdict: "Может дать визуальное сглаживание и мягкость по длине за счёт Amodimethicone, Dimethicone, Cyclopentasiloxane и катионных кондиционеров.",
    caution: "Для нормальных волос состав выглядит перегруженным: жирные спирты, катионные кондиционеры и силиконы стоят слишком высоко. Есть Alcohol, DMDM Hydantoin, Methylchloroisothiazolinone и Methylisothiazolinone. Это не лучший вариант для регулярного базового мытья.",
    inci: "Aqua, Sodium Laureth Sulfate, Cetyl Alcohol, Steartrimonium Chloride, Cetearyl Alcohol, Hydroxyethylcellulose, Amodimethicone, Cyclopentasiloxane, Dimethicone, Alcohol, Trideceth-10, Cetrimonium Chloride, Parfum, Argania Spinosa Kernel Oil, DMDM Hydantoin, Citric Acid, Methylchloroisothiazolinone, Methylisothiazolinone, Sodium Chloride, CI 15985, CI 16255, CI 42090, CI 19140",
  },
  {
    id: 10,
    name: "DETOX очищение",
    brandNote: "DEONICA",
    score: 72,
    price: 713,
    fit: ["normal", "oily"],
    base: "Хорошая смешанная ПАВ-система с кондиционирующими полимерами, но с ментолом и MCI/MI.",
    signals: ["сильная ПАВ-система", "есть Zinc PCA", "ментол и MCI/MI"],
    verdict: "SLES хорошо сбалансирован amphodiacetate, CAPB, lauryl glucoside и sarcosinate. Есть Polyquaternium-10 и Polyquaternium-7 для скольжения, а Zinc PCA делает формулу уместной для более жирной кожи головы.",
    caution: "Menthol может раздражать чувствительную кожу и не всем нужен в повседневном шампуне. Methylchloroisothiazolinone и Methylisothiazolinone снижают привлекательность для чувствительной кожи. Detox — скорее маркетинговое слово, чем реальная функция.",
    inci: "Aqua, Sodium Laureth Sulfate, Disodium Cocoamphodiacetate, Cocamidopropyl Betaine, Lauryl Glucoside, Sodium Lauroyl Sarcosinate, Polyquaternium-10, Zinc PCA, Polyquaternium-7, PPG-3 Caprylyl Ether, Lactic Acid, PEG-40 Hydrogenated Castor Oil, Parfum, Menthol, Citric Acid, Sodium Chloride, Disodium EDTA, Methylchloroisothiazolinone, Methylisothiazolinone, Citral, Limonene",
  },
  {
    id: 11,
    name: "Шампунь увлажняющий для волос L.OVE",
    brandNote: "Faberlic",
    score: 67,
    price: 1040,
    fit: ["normal"],
    base: "Нормальный мягкий SLES-шампунь с кондиционированием, но немного тяжеловатый.",
    signals: ["рабочий середняк", "есть cationic guar", "может утяжелять"],
    verdict: "SLES + CAPB — обычная база, дополненная Glycereth-2 Cocoate, Guar Hydroxypropyltrimonium Chloride и Cetyl Alcohol. Нет MCI/MI, что выглядит лучше многих похожих составов.",
    caution: "Lanolin и жирные компоненты высоко в составе могут быть лишними для нормальных волос и давать утяжеление. Формула не плохая, но не выглядит особенно современной или выдающейся за свою цену.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Lanolin, Glycereth-2 Cocoate, Cocamide MEA, Guar Hydroxypropyltrimonium Chloride, Cetyl Alcohol, Glycol Distearate, Sodium Dextran Sulfate, Sodium Benzoate, Sodium Salicylate, Citric Acid, Disodium EDTA, Parfum, Amyl Cinnamal, Hexyl Cinnamal",
  },
  {
    id: 12,
    name: "CUREX CLASSIC увлажняющий",
    brandNote: "ESTEL",
    score: 48,
    price: 1960,
    fit: ["normal"],
    base: "Старомодная SLES/DEA-формула с большим маркетинговым хвостом.",
    signals: ["Cocamide DEA высоко", "много декоративных активов", "MCI/MI"],
    verdict: "Есть Decyl Glucoside, Betaine, Panthenol, Polyquaternium-10 и увлажняющие добавки, поэтому формула не пустая.",
    caution: "Cocamide DEA стоит очень высоко, а большая часть кератина, витаминов, гиалуроната, биотина и растительных компонентов выглядит как маркетинговый хвост. Есть Methylchloroisothiazolinone и Methylisothiazolinone. За эту цену состав выглядит слабым.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamide DEA, Glycol Distearate, Cocamidopropyl Betaine, Decyl Glucoside, Sodium Chloride, Hydrolyzed Keratin, Betaine, PEG-35 Castor Oil, Polysorbate 20, Aesculus Hippocastanum Seed Extract, Retinyl Palmitate, Tocopherol, Inositol, Calcium Pantothenate, Linoleic Acid, Biotin, Glycerin, Propylene Glycol, Sorbitol, Panthenol, Carboxymethyl Chitin, Sodium Hyaluronate, Parfum, Limonene, Hexyl Cinnamal, Linalool, Polyquaternium-10, Citric Acid, Lecithin, Methylchloroisothiazolinone, Methylisothiazolinone",
  },
  {
    id: 13,
    name: "Восстанавливающий с алоэ",
    brandNote: "Faberlic",
    score: 52,
    price: 489,
    fit: ["normal"],
    base: "Потенциально мягкая формула, но состав выглядит неполным или странно записанным.",
    signals: ["нет Aqua в начале", "pH 4.0–4.9", "сомнительная структура"],
    verdict: "CAPB и Disodium Laureth Sulfosuccinate — мягкое начало, pH 4.0–4.9 выглядит удачно, Polyquaternium-10 может улучшать скольжение.",
    caution: "Для обычного жидкого шампуня отсутствие Aqua выглядит подозрительно. Масла и экстракты стоят слишком высоко, что может означать ошибку карточки или неполный состав. Есть Methylchloroisothiazolinone и Methylisothiazolinone. Без проверки фото упаковки рейтинг лучше считать условным.",
    inci: "Cocamidopropyl Betaine, Disodium Laureth Sulfosuccinate, Helianthus Annuus Seed Oil, Zea Mays Germ Oil, Citrus Medica Limonum Fruit Extract, Prunus Armeniaca Kernel Oil, Hydrogenated Apricot Kernel Oil, Tocopherol, Parfum, Polyquaternium-10, Citric Acid, Sodium Chloride, Magnesium Nitrate, Magnesium Chloride, Methylchloroisothiazolinone, Methylisothiazolinone",
  },
  {
    id: 15,
    name: "sea says yes Шампунь для всех типов волос",
    brandNote: "VOIS",
    score: 61,
    price: 792,
    fit: ["normal", "oily"],
    base: "Активно очищающий шампунь на Olefin Sulfonate с большим смягчающим блоком.",
    signals: ["сильное очищение", "много смягчения", "перегруженный состав"],
    verdict: "Формула пытается смягчить сильную моющую базу: есть CAPB, coco-glucoside, glyceryl oleate, amphodiacetate, sarcosinate, glycerin, panthenol, allantoin, cationic guar и Polyquaternium-10.",
    caution: "Sodium C14-16 Olefin Sulfonate на втором месте делает шампунь более очищающим, чем хотелось бы для универсального варианта на каждый день. Много гиалуронатов, масел и экстрактов в хвосте выглядят скорее декоративно. Лучше для жирной кожи головы, чем для чувствительной или сухой.",
    inci: "Aqua, Sodium C14-16 Olefin Sulfonate, Cocamidopropyl Betaine, Glycerin, Coco-Glucoside, Glyceryl Oleate, Disodium Cocoamphodiacetate, Cocamide Methyl MEA, Sodium Chloride, Sodium Lauroyl Sarcosinate, Panthenol, C12-13 Alkyl Lactate, Allantoin, Phenoxyethanol, Maltooligosyl Glucoside, Sodium Benzoate, Citric Acid, Guar Hydroxypropyltrimonium Chloride, Hydrogenated Starch Hydrolysate, Fragrance, Chamomilla Recutita Flower Extract, Polyquaternium-10, Cocos Nucifera Oil, Simmondsia Chinensis Seed Oil, Butylene Glycol, Hydroxyacetophenone, Pentylene Glycol, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Tocopherol, Sodium Hyaluronate Crosspolymer, Hydrogenated Palm Glycerides Citrate, Hydrolyzed Sodium Hyaluronate, Ethylhexylglycerin",
  },
  {
    id: 16,
    name: "Мужской шампунь для волос 2в1",
    brandNote: "FABRIK Cosmetology, ДРУГОЙ состав по старой карточке",
    score: 46,
    price: 366,
    fit: ["normal", "oily"],
    base: "В отзывах нашли версию с новым составом: обычная SLES-база с солью, Cocamide DEA и DMDM Hydantoin. Оценка оригинальной версии не применима к этой версии состава.",
    signals: ["другой состав", "DMDM Hydantoin"],
    verdict: "Есть рабочая моющая база: SLES, sulfosuccinate, CAPB и lauryl glucoside. Для жирной кожи головы может промывать достаточно активно.",
    caution: "Состав заметно слабее старой версии: Sodium Chloride стоит слишком высоко, есть Cocamide DEA, DMDM Hydantoin, ментоловый/мятный компонент и аллерген D-Limonene. Активы вроде кофеина, таурина, пантенола и ниацинамида выглядят второстепенно. Старый высокий рейтинг к этой версии применять нельзя.",
    inci: "Aqua, Sodium Laureth Sulfate, Sodium Chloride, Disodium Lauryl Sulfosuccinate, Cocamide DEA, Cocamidopropyl Betaine, Lauryl Glucoside, DMDM Hydantoin, Caffeine, Fragrance, Glycerin, Taurine, Panthenol, Mentha Piperita Oil, Niacinamide, Verbena Officinalis Leaf Extract, Limonene, Sodium Hydroxide, Tetrasodium EDTA, Citric Acid, Tocopherol",
  },
  {
    id: 17,
    name: "Шампунь от перхоти лечебный с цинком",
    brandNote: "КНЯЖЕВИКА",
    score: 50,
    price: 4315,
    fit: ["oily"],
    base: "Мягкая бессульфатная база, но состав выглядит неполным и плохо подтверждает статус лечебного шампуня от перхоти.",
    signals: ["мягкая ПАВ-база", "сомнительная консервация", "цена высоковата"],
    verdict: "Начало состава хорошее: Sodium Lauroyl Sarcosinate, Cocamidopropyl Betaine, Betaine, Glycerin и Coco-Glucoside. pH 4.8 тоже выглядит удачно.",
    caution: "В составе не видно полноценной консервирующей системы для водного продукта с экстрактами и белком. Zinc PCA — полезный себорегулирующий компонент, но это не полноценное доказательство лечебного действия против перхоти. Эфирные масла иланг-иланга, эвкалипта и чайного дерева повышают риск раздражения. При этом цена кусается.",
    inci: "Aqua, Sodium Lauroyl Sarcosinate, Cocamidopropyl Betaine, Betaine, Glycerin, Coco-Glucoside, Hydrolyzed Wheat Protein, Maris Sal, Zinc PCA, Pyridoxine HCl, Allantoin, Cananga Odorata Flower Oil, Lactic Acid, Tocopherol, Rosa Canina Fruit Oil, Eucalyptus Globulus Leaf Oil, Melaleuca Alternifolia Leaf Oil, Urtica Dioica Extract, Chamomilla Recutita Extract, Bidens Tripartita Extract",
  },
  {
    id: 18,
    name: "EASY Шампунь гипоаллергенный без запаха и отдушек",
    brandNote: "Allergikoff",
    score: 79,
    price: 1440,
    fit: ["normal", "oily", "sensitive"],
    base: "Минималистичный шампунь без отдушки с pH 5.5; один из самых честных вариантов для чувствительной кожи головы.",
    signals: ["без отдушки", "pH 5.5", "минималистичный состав"],
    verdict: "Короткая и аккуратная формула: SLES дополнен Sodium Laureth-11 Carboxylate, есть мягкие смягчающие компоненты, Polyquaternium-10 и нормальная консервация. Хороший выбор, если важнее переносимость, а не вау-сенсорика.",
    caution: "Формула проще, чем у лидеров по универсальности. Нет богатой смешанной ПАВ-системы с CAPB, glucoside, amphoacetate или sulfosuccinate. Никакого запаха, цвета и маркетингового хвоста.",
    inci: "Aqua, Sodium Laureth Sulfate, Sodium Laureth-11 Carboxylate, Glycereth-2 Cocoate, PEG-4 Rapeseedamide, Polyquaternium-10, Citric Acid, Sodium Benzoate",
  },
  {
    id: 19,
    name: "Мужской шампунь для волос 2в1",
    brandNote: "FABRIK Cosmetology",
    score: 82,
    price: 366,
    fit: ["normal", "oily"],
    base: "Очень сильный состав за свою цену: хорошая смешанная ПАВ-система, pH 5.5 и приличное кондиционирование.",
    signals: ["лучшее соотношение цена/состав", "pH 5.5", "проверять состав партии!"],
    verdict: "Оригинальная версия выглядит неожиданно грамотно: SLES сбалансирован CAPB, sulfosuccinate, lauryl glucoside и cocoamphoacetate. Есть глицерин, PEG-7 Glyceryl Cocoate, Polyquaternium-7, cationic guar и Polyquaternium-10. Это хороший повседневный шампунь, а не просто дешёвый масс-маркет.",
    caution: "Критически важно сверять состав на конкретной бутылке. По новой (возможно промежуточной) партии состав сильно ухудшили: появились Cocamide DEA, DMDM Hydantoin и более грубая структура базы.",
    inci: "Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Glycerin, PEG-4 Rapeseedamide, Disodium Lauryl Sulfosuccinate, Sodium Chloride, Lauryl Glucoside, Sodium Cocoamphoacetate, Glycol Distearate, Polyquaternium-7, PEG-7 Glyceryl Cocoate, Caffeine, Fragrance, PEG-40 Hydrogenated Castor Oil, Taurine, Panthenol, Guar Hydroxypropyltrimonium Chloride, Citric Acid, Potassium Sorbate, Niacinamide, Verbena Officinalis Extract, Melissa Officinalis Leaf Extract, Sodium Benzoate, Benzyl Alcohol, Tetrasodium Glutamate Diacetate, Polyquaternium-10, Tocopherol",
  },
  {
    id: 20,
    name: "Detox Абрикосовое варение и шелковица бессульфатный",
    brandNote: "Metodologia",
    score: 79,
    price: 1092,
    fit: ["normal", "sensitive"],
    base: "Хороший мягкий бессульфатный шампунь на sulfosuccinate, sarcosinate и CAPB.",
    signals: ["мягкая бессульфатная база", "без SLES", "слабое кондиционирование"],
    verdict: "ПАВ-база выглядит удачно: Disodium Lauryl Sulfosuccinate, Sodium Lauroyl Sarcosinate и Cocamidopropyl Betaine. Есть глицерин, мягкая консервация Sodium Benzoate + Potassium Sorbate и хелатор Tetrasodium Glutamate Diacetate.",
    caution: "Название Detox — маркетинг, не функциональное преимущество. Кондиционирующий блок слабее, чем у лучших конкурентов: обычная guar gum не равна cationic guar. Эфирное масло плюмерии и fragrance могут быть минусом для очень чувствительной кожи.",
    inci: "Aqua, Disodium Lauryl Sulfosuccinate, Sodium Lauroyl Sarcosinate, Cocamidopropyl Betaine, Glycerin, Sodium Benzoate, Potassium Sorbate, Glycol Distearate, Chamomilla Recutita Flower Extract, Cyamopsis Tetragonoloba Gum, Plumeria Rubra Essential Oil, Tetrasodium Glutamate Diacetate, Citric Acid, Fragrance, Glutamic Acid, Cucumis Sativus Fruit Extract, Simmondsia Chinensis Seed Oil, Hydrolyzed Silk Protein, Cocos Nucifera Oil, Tocopherol, Camellia Sinensis Leaf Extract, CI 75130",
  },
];
